/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

import br.com.infox.dal.ModuloConexao;
import java.text.*;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import objetos.GeradorRelatorios;



/**
 *
 * @author Leonardo
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        trocaIcone();
        conexao = ModuloConexao.conector();
    }
    
    //metodo responsavel pro dar um icone a execução do sistema
    private void trocaIcone(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconesistema.png")));       
    }
    
    public static void abrirTelaIntegracao1(){
        
        TelaIntegracao1 integracao1 = new TelaIntegracao1();
        integracao1.setVisible(true);
        desktop.add(integracao1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        ImageIcon icon=new ImageIcon(getClass().getResource("fundo.jpg"));
        Image img=icon.getImage();
        desktop = new javax.swing.JDesktopPane() {

            public void paintComponent (Graphics g){
                g.drawImage(img, 0, 0, getWidth(),
                    getHeight(), this);
            }
        };
        jToolBar3 = new javax.swing.JToolBar();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        lblEmpId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        lblUsuarioId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        lblData1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnFerramentaCadPes = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnFerramentaCadPes2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnFerramentaCadPes1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnFerramentaCadPes3 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnFerramentaCadPes4 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnFerramentaCadPes5 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadPes = new javax.swing.JMenuItem();
        menCadEmp = new javax.swing.JMenuItem();
        menCadVei = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menIntegracao = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menAcessoPV = new javax.swing.JMenuItem();
        menAcessoGerenciador = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menPes = new javax.swing.JMenu();
        menPesAvu = new javax.swing.JMenuItem();
        menPesDup = new javax.swing.JMenuItem();
        menPesPes = new javax.swing.JMenuItem();
        menOs = new javax.swing.JMenu();
        menOsGerar = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        menRelGerador = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menParametros = new javax.swing.JMenuItem();
        menCadUsu = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menSai = new javax.swing.JMenuItem();
        menAju = new javax.swing.JMenu();

        setTitle("DEV - Sistema de Gestão - LvSoftware");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1600, 860));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(1500, 960));

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);
        jToolBar3.add(jSeparator9);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Versão: 1.0.1A");
        jToolBar3.add(jLabel1);
        jToolBar3.add(jSeparator10);

        lblEmpId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmpId.setText("ID");
        jToolBar3.add(lblEmpId);

        jLabel3.setText(" - ");
        jToolBar3.add(jLabel3);

        lblEmpresa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblEmpresa.setText("Nome da Empresa");
        jToolBar3.add(lblEmpresa);
        jToolBar3.add(jSeparator11);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Usuário: ");
        jToolBar3.add(jLabel2);

        lblUsuarioId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuarioId.setText("ID");
        jToolBar3.add(lblUsuarioId);

        jLabel4.setText(" - ");
        jToolBar3.add(jLabel4);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblUsuario.setText("Nome do Usuário");
        jToolBar3.add(lblUsuario);
        jToolBar3.add(jSeparator12);

        lblData1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblData1.setText("Data Atual:  ");
        jToolBar3.add(lblData1);

        lblData.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblData.setText("Data");
        jToolBar3.add(lblData);
        jToolBar3.add(jSeparator13);

        desktop.setLayer(jToolBar3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 1526, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap(920, Short.MAX_VALUE)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        btnFerramentaCadPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/cadastro de pessoas.png"))); // NOI18N
        btnFerramentaCadPes.setFocusable(false);
        btnFerramentaCadPes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFerramentaCadPes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFerramentaCadPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentaCadPesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFerramentaCadPes);
        jToolBar1.add(jSeparator3);

        btnFerramentaCadPes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/empresas.png"))); // NOI18N
        btnFerramentaCadPes2.setFocusable(false);
        btnFerramentaCadPes2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFerramentaCadPes2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFerramentaCadPes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentaCadPes2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFerramentaCadPes2);
        jToolBar1.add(jSeparator4);

        btnFerramentaCadPes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/car-icon.png"))); // NOI18N
        btnFerramentaCadPes1.setFocusable(false);
        btnFerramentaCadPes1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFerramentaCadPes1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFerramentaCadPes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentaCadPes1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFerramentaCadPes1);
        jToolBar1.add(jSeparator5);

        btnFerramentaCadPes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/integracao.png"))); // NOI18N
        btnFerramentaCadPes3.setFocusable(false);
        btnFerramentaCadPes3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFerramentaCadPes3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFerramentaCadPes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentaCadPes3ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFerramentaCadPes3);
        jToolBar1.add(jSeparator6);

        btnFerramentaCadPes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/user-id-icon.png"))); // NOI18N
        btnFerramentaCadPes4.setFocusable(false);
        btnFerramentaCadPes4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFerramentaCadPes4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFerramentaCadPes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentaCadPes4ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFerramentaCadPes4);
        jToolBar1.add(jSeparator7);

        btnFerramentaCadPes5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/CardAcesso 32 (1).png"))); // NOI18N
        btnFerramentaCadPes5.setFocusable(false);
        btnFerramentaCadPes5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFerramentaCadPes5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFerramentaCadPes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentaCadPes5ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFerramentaCadPes5);
        jToolBar1.add(jSeparator8);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/checklist.png"))); // NOI18N
        jButton1.setToolTipText("CheckList - Farelo");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        menCad.setText("Cadastro");
        menCad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menCadPes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menCadPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/cadastro de pessoas.png"))); // NOI18N
        menCadPes.setText("Pessoas");
        menCadPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadPesActionPerformed(evt);
            }
        });
        menCad.add(menCadPes);

        menCadEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menCadEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/empresas.png"))); // NOI18N
        menCadEmp.setText("Empresas");
        menCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadEmpActionPerformed(evt);
            }
        });
        menCad.add(menCadEmp);

        menCadVei.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menCadVei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/car-icon.png"))); // NOI18N
        menCadVei.setText("Veículos");
        menCadVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadVeiActionPerformed(evt);
            }
        });
        menCad.add(menCadVei);
        menCad.add(jSeparator14);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/mais.png"))); // NOI18N
        jMenu5.setText("Complementares");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/maps.png"))); // NOI18N
        jMenuItem6.setText("Destinos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        menCad.add(jMenu5);

        Menu.add(menCad);

        jMenu2.setText("Integração");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menIntegracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menIntegracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/integracao.png"))); // NOI18N
        menIntegracao.setText("Integracão");
        menIntegracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIntegracaoActionPerformed(evt);
            }
        });
        jMenu2.add(menIntegracao);

        Menu.add(jMenu2);

        jMenu1.setText("Controle de Acesso");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menAcessoPV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menAcessoPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/user-id-icon.png"))); // NOI18N
        menAcessoPV.setText("Veículos e Pessoas");
        menAcessoPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAcessoPVActionPerformed(evt);
            }
        });
        jMenu1.add(menAcessoPV);

        menAcessoGerenciador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menAcessoGerenciador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/CardAcesso 32 (1).png"))); // NOI18N
        menAcessoGerenciador.setText("Gerenciador");
        menAcessoGerenciador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAcessoGerenciadorActionPerformed(evt);
            }
        });
        jMenu1.add(menAcessoGerenciador);

        Menu.add(jMenu1);

        jMenu4.setText("CheckList");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/checklist.png"))); // NOI18N
        jMenuItem5.setText("Carregamento de Farelo - RQ_SLG 10.02");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/1622833_checkmark_done_exam_list_pencil_icon.png"))); // NOI18N
        jMenuItem7.setText("Demonstrativo - RQ_SLG1002");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        Menu.add(jMenu4);

        menPes.setText("Pesagem");
        menPes.setEnabled(false);
        menPes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menPesAvu.setText("PesagemAberta");
        menPesAvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPesAvuActionPerformed(evt);
            }
        });
        menPes.add(menPesAvu);

        menPesDup.setText("Pesagem Dupla (Rodotrem)");
        menPes.add(menPesDup);

        menPesPes.setText("Pesagem");
        menPesPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPesPesActionPerformed(evt);
            }
        });
        menPes.add(menPesPes);

        Menu.add(menPes);

        menOs.setText("Os");
        menOs.setEnabled(false);
        menOs.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOsActionPerformed(evt);
            }
        });

        menOsGerar.setText("Gerar ordem de serviço");
        menOsGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOsGerarActionPerformed(evt);
            }
        });
        menOs.add(menOsGerar);

        Menu.add(menOs);

        menRel.setText("Relatório");
        menRel.setEnabled(false);
        menRel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu7.setText("Cadastros");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu8.setText("Pessoas");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem8.setText("Relatório (Geral)");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem28.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem28.setText("Motoristas");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem28);

        jMenuItem29.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem29.setText("Visitantes");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem29);

        jMenuItem30.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem30.setText("Terceiros");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem30);

        jMenuItem31.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem31.setText("Funcionários");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem31);

        jMenu7.add(jMenu8);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu10.setText("Veículos");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem13.setText("Relatório (Geral)");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem13);

        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem27.setText("Veículos de Carga");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem27);

        jMenu7.add(jMenu10);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu9.setText("Empresas");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem14.setText("Relatório (Geral)");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem14);

        jMenuItem25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem25.setText("Cliente");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem25);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem26.setText("Cliente/Fornecedor");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem26);

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem24.setText("Transportadoras");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem24);

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem23.setText("Tercerizadas");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem23);

        jMenu7.add(jMenu9);

        menRel.add(jMenu7);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu6.setText("Integracão");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem1.setText("Relatório de empresas ativas (Geral)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem9.setText("Relatório de empresas ativas (Tercerizadas)");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem10.setText("Relatório de integrados ativos (Geral)");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem11.setText("Relatório de integrados ativos (Empresa)");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        menRel.add(jMenu6);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu12.setText("Acesso");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem15.setText("Relatório de acesso por pessoas (ID)");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem16.setText("Relatório de acesso por veículos (Placa)");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem16);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem18.setText("Relatório de acesso por empresa (ID)");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem18);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem17.setText("Relatório de acesso por período (Data)");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem17);

        menRel.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu13.setText("ChecList");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu14.setText("Pessoas");
        jMenu14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem19.setText("Relatório (Geral)");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem19);

        jMenuItem20.setText("jMenuItem12");
        jMenu14.add(jMenuItem20);

        jMenu13.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu15.setText("Veículos");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem21.setText("Relatório (Geral)");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem21);

        jMenu13.add(jMenu15);

        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenu16.setText("Empresas");
        jMenu16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem22.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/impressora32.png"))); // NOI18N
        jMenuItem22.setText("Relatório (Geral)");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem22);

        jMenu13.add(jMenu16);

        menRel.add(jMenu13);

        menRelGerador.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        menRelGerador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/print.png"))); // NOI18N
        menRelGerador.setText("Gerador de Relatorios");
        menRelGerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelGeradorActionPerformed(evt);
            }
        });
        menRel.add(menRelGerador);

        Menu.add(menRel);

        jMenu3.setText("Sistema");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menParametros.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/pastaconfiguracaoverde.png"))); // NOI18N
        menParametros.setText("Parâmetros do Sistema");
        menParametros.setEnabled(false);
        menParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menParametrosActionPerformed(evt);
            }
        });
        jMenu3.add(menParametros);

        menCadUsu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/pastapessoaamarela.png"))); // NOI18N
        menCadUsu.setText("Usuários");
        menCadUsu.setEnabled(false);
        menCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuActionPerformed(evt);
            }
        });
        jMenu3.add(menCadUsu);

        Menu.add(jMenu3);

        menOpc.setText("Opções");
        menOpc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        menSai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menSai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/close.png"))); // NOI18N
        menSai.setText("Sair");
        menSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSaiActionPerformed(evt);
            }
        });
        menOpc.add(menSai);

        menAju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/ajuda.png"))); // NOI18N
        menAju.setText("Ajuda");
        menAju.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menOpc.add(menAju);

        Menu.add(menOpc);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1526, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As linhas subistiruem a caixa de data pela data atual
        Date data = new Date();
        DateFormat formatador;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        //formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formato.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void menSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSaiActionPerformed
        //Exibe uma caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0); //sai do sistema
        }
    }//GEN-LAST:event_menSaiActionPerformed

    private void menCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuActionPerformed
        //abre internamente o formulario
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
        usuario.moveToFront();
    }//GEN-LAST:event_menCadUsuActionPerformed

    private void menOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOsActionPerformed

    }//GEN-LAST:event_menOsActionPerformed

    private void menOsGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOsGerarActionPerformed
        TelaOs os = new TelaOs();
        os.setVisible(true);
        desktop.add(os);
        os.moveToFront();
    }//GEN-LAST:event_menOsGerarActionPerformed

    private void menAcessoPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAcessoPVActionPerformed
        TelaControleAcesso controle = new TelaControleAcesso();
        controle.setVisible(true);
        desktop.add(controle);
        controle.moveToFront();
    }//GEN-LAST:event_menAcessoPVActionPerformed

    private void menIntegracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIntegracaoActionPerformed
        TelaIntegracao integracao = new TelaIntegracao();
        integracao.setVisible(true);
        desktop.add(integracao);
        integracao.moveToFront();
    }//GEN-LAST:event_menIntegracaoActionPerformed

    private void menAcessoGerenciadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAcessoGerenciadorActionPerformed
        TelaAcessoAtivo ativo = new TelaAcessoAtivo();
        ativo.setVisible(true);
        desktop.add(ativo);
        ativo.moveToFront();
    }//GEN-LAST:event_menAcessoGerenciadorActionPerformed

    private void menParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menParametrosActionPerformed
        TelaParametros parametros = new TelaParametros();
        parametros.setVisible(true);
        desktop.add(parametros);
        parametros.moveToFront();
    }//GEN-LAST:event_menParametrosActionPerformed

    private void btnFerramentaCadPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentaCadPesActionPerformed
        // chamando a tela Pessoas
        TelaPessoa pessoa =new TelaPessoa();
        pessoa.setVisible(true);
        desktop.add(pessoa);
        pessoa.moveToFront();
    }//GEN-LAST:event_btnFerramentaCadPesActionPerformed

    private void btnFerramentaCadPes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentaCadPes2ActionPerformed
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);
        cliente.moveToFront();
    }//GEN-LAST:event_btnFerramentaCadPes2ActionPerformed

    private void btnFerramentaCadPes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentaCadPes1ActionPerformed
        TelaVeiculos veiculo = new TelaVeiculos();
        veiculo.setVisible(true);
        desktop.add(veiculo);
        veiculo.moveToFront();
    }//GEN-LAST:event_btnFerramentaCadPes1ActionPerformed

    private void btnFerramentaCadPes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentaCadPes3ActionPerformed
        TelaIntegracao integracao = new TelaIntegracao();
        integracao.setVisible(true);
        desktop.add(integracao);
        integracao.moveToFront();
    }//GEN-LAST:event_btnFerramentaCadPes3ActionPerformed

    private void btnFerramentaCadPes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentaCadPes4ActionPerformed
        TelaControleAcesso controle = new TelaControleAcesso();
        controle.setVisible(true);
        desktop.add(controle);
        controle.moveToFront();
    }//GEN-LAST:event_btnFerramentaCadPes4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaCheckList checklist = new TelaCheckList();
        checklist.setVisible(true);
        desktop.add(checklist);
        checklist.moveToFront();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaCheckList checklist = new TelaCheckList();
        checklist.setVisible(true);
        desktop.add(checklist);
        checklist.moveToFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menCadVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadVeiActionPerformed
        TelaVeiculos veiculo = new TelaVeiculos();
        veiculo.setVisible(true);
        desktop.add(veiculo);
        veiculo.moveToFront();
    }//GEN-LAST:event_menCadVeiActionPerformed

    private void menCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadEmpActionPerformed
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);
        cliente.moveToFront();
    }//GEN-LAST:event_menCadEmpActionPerformed

    private void menCadPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadPesActionPerformed
        // chamando a tela Pessoas
        TelaPessoa pessoa =new TelaPessoa();
        pessoa.setVisible(true);
        desktop.add(pessoa);
        pessoa.moveToFront();
    }//GEN-LAST:event_menCadPesActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // chamando a tela Destinos
        TelaDestinos destino =new TelaDestinos();
        destino.setVisible(true);
        desktop.add(destino);
        destino.moveToFront();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menPesPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPesPesActionPerformed
        TelaPesagemAvulsa pesagem = new TelaPesagemAvulsa();
        pesagem.setVisible(true);
        desktop.add(pesagem);
    }//GEN-LAST:event_menPesPesActionPerformed

    private void menPesAvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPesAvuActionPerformed
        //abre internamente o formulario
        TelaPesagem pesagem = new TelaPesagem();
        pesagem.setVisible(true);
        desktop.add(pesagem);
    }//GEN-LAST:event_menPesAvuActionPerformed

    private void menRelGeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelGeradorActionPerformed

    }//GEN-LAST:event_menRelGeradorActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TelaCheckListGerenciador checklistg = new TelaCheckListGerenciador();
        checklistg.setVisible(true);
        desktop.add(checklistg);
        checklistg.moveToFront();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btnFerramentaCadPes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentaCadPes5ActionPerformed
        TelaAcessoAtivo ativo = new TelaAcessoAtivo();
        ativo.setVisible(true);
        desktop.add(ativo);
        ativo.moveToFront();
    }//GEN-LAST:event_btnFerramentaCadPes5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GeradorRelatorios relatorio = new GeradorRelatorios();
        relatorio.relatoriointegracaoempresas();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        GeradorRelatorios relatorio = new GeradorRelatorios();
        relatorio.relatoriointegracaoempresastercerizadas();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        GeradorRelatorios relatorio = new GeradorRelatorios();
        relatorio.relatoriointegracaointegradosgeral();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        GeradorRelatorios relatorio = new GeradorRelatorios();
        relatorio.relatoriointegracaointegradosempresa(); //precisa de parametro
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
        
        try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
    //java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton btnFerramentaCadPes;
    private javax.swing.JButton btnFerramentaCadPes1;
    private javax.swing.JButton btnFerramentaCadPes2;
    private javax.swing.JButton btnFerramentaCadPes3;
    private javax.swing.JButton btnFerramentaCadPes4;
    private javax.swing.JButton btnFerramentaCadPes5;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblData1;
    public static javax.swing.JLabel lblEmpId;
    public static javax.swing.JLabel lblEmpresa;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JLabel lblUsuarioId;
    private javax.swing.JMenuItem menAcessoGerenciador;
    private javax.swing.JMenuItem menAcessoPV;
    private javax.swing.JMenu menAju;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadEmp;
    private javax.swing.JMenuItem menCadPes;
    public static javax.swing.JMenuItem menCadUsu;
    private javax.swing.JMenuItem menCadVei;
    private javax.swing.JMenuItem menIntegracao;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenu menOs;
    private javax.swing.JMenuItem menOsGerar;
    public static javax.swing.JMenuItem menParametros;
    private javax.swing.JMenu menPes;
    public static javax.swing.JMenuItem menPesAvu;
    private javax.swing.JMenuItem menPesDup;
    private javax.swing.JMenuItem menPesPes;
    public static javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRelGerador;
    private javax.swing.JMenuItem menSai;
    // End of variables declaration//GEN-END:variables
}
